namespace MRI.PandA.Syncs.Functions.MixApis.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("mri_s-pmrm_residentialunitavailability", Namespace = "", IsNullable = false)]
public partial class mri_spmrm_residentialunitavailability {

  private mri_spmrm_residentialunitavailabilityEntry[] entryField;

  private string nextPageLinkField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute("entry")]
  public mri_spmrm_residentialunitavailabilityEntry[] entry {
    get {
      return this.entryField;
    }
    set {
      this.entryField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
  public string NextPageLink {
    get {
      return this.nextPageLinkField;
    }
    set {
      this.nextPageLinkField = value;
    }
  }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class mri_spmrm_residentialunitavailabilityEntry {

  private string propertyIDField;

  private string buildingIDField;

  private string unitIDField;

  private string floorplanIDField;

  private string floorplanDescriptionField;

  private string numberOfBedroomsField;

  private string numberOfBathsField;

  private string squareFeetField;

  private string isAvailableNowField;

  private string vacateDateField;

  private string makeReadyDateField;

  private string availabilityStatusField;

  private string lROField;

  private string amenityTotalField;

  private string hasImages;
  /// <remarks/>
  public string PropertyID {
    get {
      return this.propertyIDField;
    }
    set {
      this.propertyIDField = value;
    }
  }

  /// <remarks/>
  public string BuildingID {
    get {
      return this.buildingIDField;
    }
    set {
      this.buildingIDField = value;
    }
  }

  /// <remarks/>
  public string UnitID {
    get {
      return this.unitIDField;
    }
    set {
      this.unitIDField = value;
    }
  }

  /// <remarks/>
  public string FloorplanID {
    get {
      return this.floorplanIDField;
    }
    set {
      this.floorplanIDField = value;
    }
  }

  /// <remarks/>
  public string FloorplanDescription {
    get {
      return this.floorplanDescriptionField;
    }
    set {
      this.floorplanDescriptionField = value;
    }
  }

  /// <remarks/>
  public string NumberOfBedrooms {
    get {
      return this.numberOfBedroomsField;
    }
    set {
      this.numberOfBedroomsField = string.IsNullOrWhiteSpace(value) ? "0" : value;
    }
  }

  /// <remarks/>
  public string NumberOfBaths {
    get {
      return this.numberOfBathsField;
    }
    set {
      this.numberOfBathsField = string.IsNullOrWhiteSpace(value) ? "0" : value;
    }
  }

  /// <remarks/>
  public string SquareFeet {
    get {
      return this.squareFeetField;
    }
    set {
      this.squareFeetField = value;
    }
  }

  /// <remarks/>
  public string IsAvailableNow {
    get {
      return this.isAvailableNowField;
    }
    set {
      this.isAvailableNowField = value;
    }
  }

  /// <remarks/>
  public string VacateDate {
    get {
      return this.vacateDateField;
    }
    set {
      this.vacateDateField = value;
    }
  }

  /// <remarks/>
  public string MakeReadyDate {
    get {
      return this.makeReadyDateField;
    }
    set {
      this.makeReadyDateField = value;
    }
  }

  /// <remarks/>
  public string AvailabilityStatus {
    get {
      return this.availabilityStatusField;
    }
    set {
      this.availabilityStatusField = value;
    }
  }

  /// <remarks/>
  public string LRO {
    get {
      return this.lROField;
    }
    set {
      this.lROField = value;
    }
  }

  /// <remarks/>
  public string AmenityTotal {
    get {
      return this.amenityTotalField;
    }
    set {
      this.amenityTotalField = value;
    }
  }

  /// <remarks/>
  public string HasImages {
    get {
      return this.hasImages;
    }
    set {
      this.hasImages = value;
    }
  }


}
