namespace MRI.PandA.Syncs.Functions.MixApis.Schema;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("mri_s-pmrm_getrmimages", Namespace = "", IsNullable = false)]
public partial class mri_spmrm_getrmimages {

  private mri_spmrm_getrmimagesEntry[] entryField;

  private string nextPageLinkField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute("entry")]
  public mri_spmrm_getrmimagesEntry[] entry {
    get {
      return this.entryField;
    }
    set {
      this.entryField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute()]
  public string NextPageLink {
    get {
      return this.nextPageLinkField;
    }
    set {
      this.nextPageLinkField = value;
    }
  }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class mri_spmrm_getrmimagesEntry {

  private string propertyIDField;

  private string buildingIDField;

  private string unitIDField;

  private string floorplanIDField;

  private string isFloorPlanField;

  private string externalLinkField;

  /// <remarks/>
  public string PropertyID {
    get {
      return this.propertyIDField;
    }
    set {
      this.propertyIDField = value;
    }
  }

  /// <remarks/>
  public string BuildingID {
    get {
      return this.buildingIDField;
    }
    set {
      this.buildingIDField = value;
    }
  }

  /// <remarks/>
  public string UnitID {
    get {
      return this.unitIDField;
    }
    set {
      this.unitIDField = value;
    }
  }

  /// <remarks/>
  public string FloorplanID {
    get {
      return this.floorplanIDField;
    }
    set {
      this.floorplanIDField = value;
    }
  }

  /// <remarks/>
  public string IsFloorPlan {
    get {
      return this.isFloorPlanField;
    }
    set {
      this.isFloorPlanField = value;
    }
  }

  /// <remarks/>
  public string ExternalLink {
    get {
      return this.externalLinkField;
    }
    set {
      this.externalLinkField = value;
    }
  }
}