namespace MRI.PandA.Syncs.Functions.MixApis.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute("mri_s-pmrm_unitmarketrent", Namespace = "", IsNullable = false)]
public partial class mri_spmrm_unitmarketrent {

  private mri_spmrm_unitmarketrentEntry[] entryField;

  private string nextPageLinkField;

  /// <remarks/>
  [System.Xml.Serialization.XmlElementAttribute("entry")]
  public mri_spmrm_unitmarketrentEntry[] entry {
    get {
      return this.entryField;
    }
    set {
      this.entryField = value;
    }
  }

  /// <remarks/>
  [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
  public string NextPageLink {
    get {
      return this.nextPageLinkField;
    }
    set {
      this.nextPageLinkField = value;
    }
  }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class mri_spmrm_unitmarketrentEntry {

  private string propertyIDField;

  private string buildingIDField;

  private string unitIDField;

  private string classIDField;

  private string termField;

  private string startDateField;

  private string endDateField;

  private string unitRentField;

  /// <remarks/>
  public string PropertyID {
    get {
      return this.propertyIDField;
    }
    set {
      this.propertyIDField = value;
    }
  }

  /// <remarks/>
  public string BuildingID {
    get {
      return this.buildingIDField;
    }
    set {
      this.buildingIDField = value;
    }
  }

  /// <remarks/>
  public string UnitID {
    get {
      return this.unitIDField;
    }
    set {
      this.unitIDField = value;
    }
  }

  /// <remarks/>
  public string ClassID {
    get {
      return this.classIDField;
    }
    set {
      this.classIDField = value;
    }
  }

  /// <remarks/>
  public string Term {
    get {
      return this.termField;
    }
    set {
      this.termField = value;
    }
  }

  /// <remarks/>
  public string StartDate {
    get {
      return this.startDateField;
    }
    set {
      this.startDateField = value;
    }
  }

  /// <remarks/>
  public string EndDate {
    get {
      return this.endDateField;
    }
    set {
      this.endDateField = value;
    }
  }

  /// <remarks/>
  public string UnitRent {
    get {
      return this.unitRentField;
    }
    set {
      this.unitRentField = value;
    }
  }
}